import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Starbu9",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased !bg-white`} // 제가 사용하는 브라우저는 다크모드라서 추가해 뒀습니다.
      >
        <header className="flex h-24 items-center bg-[#005034]">
          <img
            src={"/images/logo.png"}
            alt="logo"
            width={100}
            height={100}
            className="pl-10"
          />
          <p className=" pl-15 text-[#F9F9F2] text-3xl font-bold">STARBU9</p>
        </header>
        {children}
      </body>
    </html>
  );
}
